version: 2.1

jobs:
  install-dep:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

workflows:
  main:
    jobs:
      - install-dep